package gmc.project.voldemart.domain;

public enum States {
	TAMIL_NADU, PONDYCHERY, KERALA, ANDRA_PRADESH, KARNATAKA, TELENGANA, ARUNACHAL_PRADESH, ASSAM, 
	BIHAR, CHHATTISGARH, GOA, GUJARAT, HARYANA, HIMACHAL_PRADESH, JHARKHAND, MADHYA_PRADESH, 
	MAHARASTRA, MANIPUR, MEGHALAYA, MIZORAM, NAGALAND, ODISHA, PUNJAB, RAJASTHAN, SIKKIM, TRIPURA, 
	UTTAR_PRADESH, UTTARAKHAND, WEST_BENGAL
}
