#logging:
#  level:
#    org.springframework.security: DEBUG

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8443
  ssl:
    key-store-password: navin@3d
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TESTING
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

#  h2:
#    console:
#      path: /h2-console
#      enabled: true
# keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore mykeystore.p12


